name: build

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PROJECT_NAME: "MiniDexed"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        builds: [{ rpi: 5 }, { rpi: 4 }, { rpi: 3 }, { rpi: 2 }, { rpi: 1 }]
    steps:
      - uses: actions/checkout@v4

      - name: Setup submodules
        run: |
          make submodules

      - name: Install toolchain
        run: |
          RPI=${{ matrix.builds.rpi }} make install-toolchain
          echo "$(pwd)/external/gcc/bin" >> $GITHUB_PATH

      - name: Build for Raspberry Pi ${{ matrix.builds.rpi }}
        run: |
          RPI=${{ matrix.builds.rpi }} make build

      - name: Build & zip Raspberry Pi boot files
        run: |
          make get-performances
          make get-sysex
          RPI=${{ matrix.builds.rpi }} make build-stub
          RPI=${{ matrix.builds.rpi }} make zip

      - uses: actions/upload-artifact@v4
        with:
          name: ${{env.PROJECT_NAME}}_rpi${{ matrix.builds.rpi }}_${{ github.sha }}
          path: ./build/sdcard/*

      - name: Release
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
          bash ./upload.sh ./build/${{env.PROJECT_NAME}}*.zip
